"""
MicroAutoML-Agent — Model Packager
Exports the final model to a standalone directory for deployment.
"""

from __future__ import annotations

import json
import logging
import pickle
import platform
import sys
from pathlib import Path
from typing import Any

import sklearn

logger = logging.getLogger(__name__)


class ModelPackager:
    """Exports pipelines and metadata into a clean `final_model/` bundle."""

    def __init__(self, output_dir: str | Path = "final_model") -> None:
        self.output_dir = Path(output_dir)

    def package(
        self,
        pipeline: Any,
        metadata: dict[str, Any],
        feature_schema: dict[str, str] | None = None
    ) -> Path:
        """
        Creates the export directory and writes all required artifacts.
        
        Args:
            pipeline: The fitted sklearn Pipeline.
            metadata: Custom metadata (seed, run_id, dataset_hash, etc).
            feature_schema: Dict of feature names to types.
            
        Returns:
            The path to the created directory.
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # 1. Serialize model
        model_path = self.output_dir / "model.pkl"
        with open(model_path, "wb") as f:
            pickle.dump(pipeline, f)
            
        # 2. Enrich and write metadata
        full_metadata = {
            "environment": {
                "python_version": sys.version,
                "os": platform.platform(),
                "sklearn_version": sklearn.__version__,
            },
            "run_info": metadata
        }
        meta_path = self.output_dir / "metadata.json"
        with open(meta_path, "w") as f:
            json.dump(full_metadata, f, indent=2)
            
        # 3. Write feature schema
        if feature_schema:
            schema_path = self.output_dir / "feature_schema.json"
            with open(schema_path, "w") as f:
                json.dump(feature_schema, f, indent=2)
                
        # 4. Generate standalone inference script
        inference_script = self._generate_inference_script()
        script_path = self.output_dir / "inference.py"
        with open(script_path, "w") as f:
            f.write(inference_script)
            
        logger.info(f"Successfully packaged final model to {self.output_dir.absolute()}")
        return self.output_dir.absolute()

    def _generate_inference_script(self) -> str:
        """Generates a standalone Python script that loads the model."""
        return '''"""
Standalone inference script generated by MicroAutoML.
Usage:
    from inference import load_model, predict
    model = load_model()
    predictions = predict(model, df)
"""

import pickle
import pandas as pd
from pathlib import Path

def load_model(model_dir="."):
    """Loads the model pipeline from the specified directory."""
    model_path = Path(model_dir) / "model.pkl"
    if not model_path.exists():
        raise FileNotFoundError(f"Model file not found at {model_path.absolute()}")
        
    with open(model_path, "rb") as f:
        return pickle.load(f)

def predict(model, data: pd.DataFrame):
    """Generates predictions using the loaded model."""
    return model.predict(data)
'''
